# Matrices
Cheatsheet regarding matrix (including vector) manipulation, arithmetic, and more.

## `numpy` Basics

### What is `numpy`?

A free and open-source Python library that provides support for multi-dimensional array. It efficiently performs operations on these multi-dimensional array a.k.a matrices and/or tensors. Operation include, but not limited to, linear algebra and statistical operations.

### Importing `numpy`

In [236]:
import numpy as np

### Creating arrays and matrices

In [237]:
# Creating numpy arrays
a = np.array([1,2,3])
a

array([1, 2, 3])

In [238]:
# Creating numpy matrices/tensors
b = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [239]:
# Zero matrix
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [240]:
# Ones matrix
np.ones([4,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [241]:
# Constant matrix (any value desired)
np.full([4,2], 777)

array([[777, 777],
       [777, 777],
       [777, 777],
       [777, 777]])

In [242]:
# Random matrix(
np.random.random((2,2))

array([[0.11222609, 0.88996179],
       [0.74156348, 0.31754343]])

In [243]:
# Identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [244]:
# Create uninitialized matrix of specific shape. Elements
# will contain random values that were already present in the 
# memory location for that matrix. Marginally faster way of creating
# matrices
np.empty([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [245]:
# create array with evenly spaced values (e.g., step values)
# by specifying the NUMBER OF DESIRED ELEMENTS
np.linspace(1, 50, 4)

array([ 1.        , 17.33333333, 33.66666667, 50.        ])

In [246]:
# create array with evenly spaced values (e.g., step values)
# by specifying the SIZE OF THE SPACE
np.arange(1,50, 4)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49])

### Matrix Information

In [247]:
a = np.array([[1,2,3], [4,5,6]])
a.shape

(2, 3)

In [248]:
b = np.array([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[4,4,4,5], [5,5,5,5], [6,6,6,6]],
])
b.shape

(2, 3, 4)

In [249]:
# retrieve length of array. NOTE: length of first dimension is returned
print(len(b)) # num sheets/dimensions
print(len(b[0])) # num rows
print(len(b[0][0]))
print(b.ndim) # number of dimensions
print(b.size) # num of elements

2
3
4
3
24


In [250]:
b.shape

(2, 3, 4)

### Matrix Arithmetic

#### Element-wise Addition, Substraction, Multiplication, and Division

In [251]:
# addition and subtraction
a = np.ones((2,2))
print(a)
b = np.array([
    [1, 1],
    [2, 3],
])
print(b)

a + b # or np.add(b, a)

[[1. 1.]
 [1. 1.]]
[[1 1]
 [2 3]]


array([[2., 2.],
       [3., 4.]])

In [252]:
a - b # or np.subtract(a, b)

array([[ 0.,  0.],
       [-1., -2.]])

In [253]:
# Element-wise Multiplication and Division (operands must have the same shape)
c = np.eye(3,3)
print(c)
d = np.array([
    [3,3,3], 
    [4,4,4],
    [5,5,5]
])
print(d)
c * d # same as np.multiply(c,d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[3 3 3]
 [4 4 4]
 [5 5 5]]


array([[3., 0., 0.],
       [0., 4., 0.],
       [0., 0., 5.]])

In [254]:
e = np.full((3,3), 2)
d / e # same as np.divide(d,e)

array([[1.5, 1.5, 1.5],
       [2. , 2. , 2. ],
       [2.5, 2.5, 2.5]])

#### Element-wise Comparison

In [255]:
a = np.full((2,2), 10);
b = np.array([
    [-10,10],
    [11, 500]
])
print(a < b)    # Element wise comparison
print(a == b)   # Element wise equality comparison

[[False False]
 [ True  True]]
[[False  True]
 [False False]]


#### Dot Product and Matrix Multiplication

In [256]:
# Dot Product
a = np.array([1,0,3])
b = np.array([2,2,4])
a.dot(b)

14

In [257]:
# Matrix Multiplication (NOTE: a.matmul(b) only works if a has shape
# (m,n) and b has shape (n,p), result will have shape (m,p))
a = np.array([
    [1,2,3]
])
print(a)
b = np.array([
    [2, 0],
    [3, 1],
    [0, 2]
])
print(b)
np.matmul(a,b)

[[1 2 3]]
[[2 0]
 [3 1]
 [0 2]]


array([[8, 8]])

#### Aggregate Functions

See: https://numpy.org/doc/stable/reference/routines.math.html 

Some common aggregate functions include:
* a.sum()
* a.min()
* a.max()
* a.mean()
* ... and more

In [258]:
print(b)
print(b.sum())
# Think of axis as the dimension of which you wish to elimate
print(b.max(axis=0)) # remove/collapse row dimension
print(b.max(axis=1)) # remove/collapse column dimension

[[2 0]
 [3 1]
 [0 2]]
8
[3 2]
[2 3 2]


## Subsettings Slicing, and Indexing

See: https://numpy.org/doc/stable/user/basics.indexing.html 

In [ ]:
# TODO